package com.kd.model.data;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("chattel_mortgage_info", "id", ChattelMortgageInfo.class);
		arp.addMapping("ent_basic_info", "id", EntBasicInfo.class);
		arp.addMapping("ent_branch_info", "id", EntBranchInfo.class);
		arp.addMapping("ent_change_info", "id", EntChangeInfo.class);
		arp.addMapping("ent_invest_info", "id", EntInvestInfo.class);
		arp.addMapping("kdata_result", "id", KdataResult.class);
		arp.addMapping("keandata", "id", Keandata.class);
		arp.addMapping("legal_person_invest_info", "id", LegalPersonInvestInfo.class);
		arp.addMapping("legal_person_position_info", "id", LegalPersonPositionInfo.class);
		arp.addMapping("liquidation_info", "id", LiquidationInfo.class);
		arp.addMapping("manage_person", "id", ManagePerson.class);
		arp.addMapping("movable_collateral_info", "id", MovableCollateralInfo.class);
		arp.addMapping("punishment_info", "id", PunishmentInfo.class);
		arp.addMapping("searchRecord", "id", SearchRecord.class);
		arp.addMapping("share_holder", "id", ShareHolder.class);
		arp.addMapping("stock_freeze_info", "id", StockFreezeInfo.class);
		arp.addMapping("stock_pledge_info", "id", StockPledgeInfo.class);
		arp.addMapping("youhao_data", "id", YouhaoData.class);
	}
}

