package com.kd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYouhaoData<M extends BaseYouhaoData<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "youhao_data";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 企业名
	 */
	public void setEntName(java.lang.String entName) {
		set("entName", entName);
	}

	/**
	 * 企业名
	 */
	public java.lang.String getEntName() {
		return get("entName");
	}

	/**
	 * 工商注册号
	 */
	public void setRegNo(java.lang.String regNo) {
		set("regNo", regNo);
	}

	/**
	 * 工商注册号
	 */
	public java.lang.String getRegNo() {
		return get("regNo");
	}

	/**
	 * 统一社会信用代码
	 */
	public void setCreditCode(java.lang.String creditCode) {
		set("creditCode", creditCode);
	}

	/**
	 * 统一社会信用代码
	 */
	public java.lang.String getCreditCode() {
		return get("creditCode");
	}

	/**
	 * 企业照面信息
	 */
	public void setBasicList(java.lang.String basicList) {
		set("basicList", basicList);
	}

	/**
	 * 企业照面信息
	 */
	public java.lang.String getBasicList() {
		return get("basicList");
	}

	/**
	 * 股东出资信息
	 */
	public void setShareHolderList(java.lang.String shareHolderList) {
		set("shareHolderList", shareHolderList);
	}

	/**
	 * 股东出资信息
	 */
	public java.lang.String getShareHolderList() {
		return get("shareHolderList");
	}

	/**
	 * 高管任职信息
	 */
	public void setPersonList(java.lang.String personList) {
		set("personList", personList);
	}

	/**
	 * 高管任职信息
	 */
	public java.lang.String getPersonList() {
		return get("personList");
	}

	/**
	 * 企业对外投资信息
	 */
	public void setEntinvItemList(java.lang.String entinvItemList) {
		set("entinvItemList", entinvItemList);
	}

	/**
	 * 企业对外投资信息
	 */
	public java.lang.String getEntinvItemList() {
		return get("entinvItemList");
	}

	/**
	 * 法定代表人对外投资信息
	 */
	public void setFrinvList(java.lang.String frinvList) {
		set("frinvList", frinvList);
	}

	/**
	 * 法定代表人对外投资信息
	 */
	public java.lang.String getFrinvList() {
		return get("frinvList");
	}

	/**
	 * 法定代表人在其他企业任职信息
	 */
	public void setFrPositionList(java.lang.String frPositionList) {
		set("frPositionList", frPositionList);
	}

	/**
	 * 法定代表人在其他企业任职信息
	 */
	public java.lang.String getFrPositionList() {
		return get("frPositionList");
	}

	/**
	 * 企业变更信息
	 */
	public void setAlterList(java.lang.String alterList) {
		set("alterList", alterList);
	}

	/**
	 * 企业变更信息
	 */
	public java.lang.String getAlterList() {
		return get("alterList");
	}

	/**
	 * 分支机构信息
	 */
	public void setFiliationList(java.lang.String filiationList) {
		set("filiationList", filiationList);
	}

	/**
	 * 分支机构信息
	 */
	public java.lang.String getFiliationList() {
		return get("filiationList");
	}

	/**
	 * 行政处罚历史信息
	 */
	public void setCaseInfoList(java.lang.String caseInfoList) {
		set("caseInfoList", caseInfoList);
	}

	/**
	 * 行政处罚历史信息
	 */
	public java.lang.String getCaseInfoList() {
		return get("caseInfoList");
	}

	/**
	 * 股权冻结历史信息
	 */
	public void setSharesFrostList(java.lang.String sharesFrostList) {
		set("sharesFrostList", sharesFrostList);
	}

	/**
	 * 股权冻结历史信息
	 */
	public java.lang.String getSharesFrostList() {
		return get("sharesFrostList");
	}

	/**
	 * 股权出质历史信息
	 */
	public void setSharesImpawnList(java.lang.String sharesImpawnList) {
		set("sharesImpawnList", sharesImpawnList);
	}

	/**
	 * 股权出质历史信息
	 */
	public java.lang.String getSharesImpawnList() {
		return get("sharesImpawnList");
	}

	/**
	 * 动产抵押信息
	 */
	public void setMorDetailList(java.lang.String morDetailList) {
		set("morDetailList", morDetailList);
	}

	/**
	 * 动产抵押信息
	 */
	public java.lang.String getMorDetailList() {
		return get("morDetailList");
	}

	/**
	 * 动产抵押物信息
	 */
	public void setMorguaInfoList(java.lang.String morguaInfoList) {
		set("morguaInfoList", morguaInfoList);
	}

	/**
	 * 动产抵押物信息
	 */
	public java.lang.String getMorguaInfoList() {
		return get("morguaInfoList");
	}

	/**
	 * 清算信息
	 */
	public void setLiquidationList(java.lang.String liquidationList) {
		set("liquidationList", liquidationList);
	}

	/**
	 * 清算信息
	 */
	public java.lang.String getLiquidationList() {
		return get("liquidationList");
	}

}
