package com.kd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockPledgeInfo<M extends BaseStockPledgeInfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "stock_pledge_info";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 企业名
	 */
	public void setEntName(java.lang.String entName) {
		set("entName", entName);
	}

	/**
	 * 企业名
	 */
	public java.lang.String getEntName() {
		return get("entName");
	}

	/**
	 * 质权人姓名
	 */
	public void setImpoRg(java.lang.String impoRg) {
		set("impoRg", impoRg);
	}

	/**
	 * 质权人姓名
	 */
	public java.lang.String getImpoRg() {
		return get("impoRg");
	}

	/**
	 * 出质人类别
	 */
	public void setImpoRgtype(java.lang.String impoRgtype) {
		set("impoRgtype", impoRgtype);
	}

	/**
	 * 出质人类别
	 */
	public java.lang.String getImpoRgtype() {
		return get("impoRgtype");
	}

	/**
	 * 出质金额
	 */
	public void setImpAm(java.lang.String impAm) {
		set("impAm", impAm);
	}

	/**
	 * 出质金额
	 */
	public java.lang.String getImpAm() {
		return get("impAm");
	}

	/**
	 * 出质备案日期
	 */
	public void setImponrecDate(java.lang.String imponrecDate) {
		set("imponrecDate", imponrecDate);
	}

	/**
	 * 出质备案日期
	 */
	public java.lang.String getImponrecDate() {
		return get("imponrecDate");
	}

	/**
	 * 出质审批部门
	 */
	public void setImpExaeep(java.lang.String impExaeep) {
		set("impExaeep", impExaeep);
	}

	/**
	 * 出质审批部门
	 */
	public java.lang.String getImpExaeep() {
		return get("impExaeep");
	}

	/**
	 * 出质批准日期
	 */
	public void setImpSanDate(java.lang.String impSanDate) {
		set("impSanDate", impSanDate);
	}

	/**
	 * 出质批准日期
	 */
	public java.lang.String getImpSanDate() {
		return get("impSanDate");
	}

	/**
	 * 出质截至日期
	 */
	public void setImpTo(java.lang.String impTo) {
		set("impTo", impTo);
	}

	/**
	 * 出质截至日期
	 */
	public java.lang.String getImpTo() {
		return get("impTo");
	}

}
