package com.kd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChattelMortgageInfo<M extends BaseChattelMortgageInfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "chattel_mortgage_info";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 企业名称
	 */
	public void setEntName(java.lang.String entName) {
		set("entName", entName);
	}

	/**
	 * 企业名称
	 */
	public java.lang.String getEntName() {
		return get("entName");
	}

	/**
	 * 抵押ID
	 */
	public void setMorregId(java.lang.String morregId) {
		set("morregId", morregId);
	}

	/**
	 * 抵押ID
	 */
	public java.lang.String getMorregId() {
		return get("morregId");
	}

	/**
	 * 抵押人
	 */
	public void setMortgaGor(java.lang.String mortgaGor) {
		set("mortgaGor", mortgaGor);
	}

	/**
	 * 抵押人
	 */
	public java.lang.String getMortgaGor() {
		return get("mortgaGor");
	}

	/**
	 * 抵押权人
	 */
	public void setMore(java.lang.String more) {
		set("more", more);
	}

	/**
	 * 抵押权人
	 */
	public java.lang.String getMore() {
		return get("more");
	}

	/**
	 * 登记机关
	 */
	public void setRegOrg(java.lang.String regOrg) {
		set("regOrg", regOrg);
	}

	/**
	 * 登记机关
	 */
	public java.lang.String getRegOrg() {
		return get("regOrg");
	}

	/**
	 * 登记日期
	 */
	public void setRegiDate(java.lang.String regiDate) {
		set("regiDate", regiDate);
	}

	/**
	 * 登记日期
	 */
	public java.lang.String getRegiDate() {
		return get("regiDate");
	}

	/**
	 * 状态标识
	 */
	public void setMorType(java.lang.String morType) {
		set("morType", morType);
	}

	/**
	 * 状态标识
	 */
	public java.lang.String getMorType() {
		return get("morType");
	}

	/**
	 * 登记证号
	 */
	public void setMorRegcno(java.lang.String morRegcno) {
		set("morRegcno", morRegcno);
	}

	/**
	 * 登记证号
	 */
	public java.lang.String getMorRegcno() {
		return get("morRegcno");
	}

	/**
	 * 申请抵押原因
	 */
	public void setAppreGrea(java.lang.String appreGrea) {
		set("appreGrea", appreGrea);
	}

	/**
	 * 申请抵押原因
	 */
	public java.lang.String getAppreGrea() {
		return get("appreGrea");
	}

	/**
	 * 被担保主债权种类
	 */
	public void setPriclasecKind(java.lang.String priclasecKind) {
		set("priclasecKind", priclasecKind);
	}

	/**
	 * 被担保主债权种类
	 */
	public java.lang.String getPriclasecKind() {
		return get("priclasecKind");
	}

	/**
	 *  被担保主债权数额(万元)
	 */
	public void setPriclaseCam(java.lang.String priclaseCam) {
		set("priclaseCam", priclaseCam);
	}

	/**
	 *  被担保主债权数额(万元)
	 */
	public java.lang.String getPriclaseCam() {
		return get("priclaseCam");
	}

	/**
	 * 履约起始日期
	 */
	public void setPefperFrom(java.lang.String pefperFrom) {
		set("pefperFrom", pefperFrom);
	}

	/**
	 * 履约起始日期
	 */
	public java.lang.String getPefperFrom() {
		return get("pefperFrom");
	}

	/**
	 * 履约截止日期
	 */
	public void setPefperTo(java.lang.String pefperTo) {
		set("pefperTo", pefperTo);
	}

	/**
	 * 履约截止日期
	 */
	public java.lang.String getPefperTo() {
		return get("pefperTo");
	}

	/**
	 * 注销日期
	 */
	public void setCanDate(java.lang.String canDate) {
		set("canDate", canDate);
	}

	/**
	 * 注销日期
	 */
	public java.lang.String getCanDate() {
		return get("canDate");
	}

}
