package com.kd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShareHolder<M extends BaseShareHolder<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "share_holder";

	/**
	 * 自增id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增id
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 企业名
	 */
	public void setEntName(java.lang.String entName) {
		set("entName", entName);
	}

	/**
	 * 企业名
	 */
	public java.lang.String getEntName() {
		return get("entName");
	}

	/**
	 * 股东名称
	 */
	public void setShareholderName(java.lang.String shareholderName) {
		set("shareholderName", shareholderName);
	}

	/**
	 * 股东名称
	 */
	public java.lang.String getShareholderName() {
		return get("shareholderName");
	}

	/**
	 * 认缴出资额（ 单位：万元）
	 */
	public void setSubConam(java.lang.String subConam) {
		set("subConam", subConam);
	}

	/**
	 * 认缴出资额（ 单位：万元）
	 */
	public java.lang.String getSubConam() {
		return get("subConam");
	}

	/**
	 * 币种
	 */
	public void setRegCapCur(java.lang.String regCapCur) {
		set("regCapCur", regCapCur);
	}

	/**
	 * 币种
	 */
	public java.lang.String getRegCapCur() {
		return get("regCapCur");
	}

	/**
	 * 出资日期
	 */
	public void setConDate(java.lang.String conDate) {
		set("conDate", conDate);
	}

	/**
	 * 出资日期
	 */
	public java.lang.String getConDate() {
		return get("conDate");
	}

	/**
	 * 出资比例
	 */
	public void setFundedRatio(java.lang.String fundedRatio) {
		set("fundedRatio", fundedRatio);
	}

	/**
	 * 出资比例
	 */
	public java.lang.String getFundedRatio() {
		return get("fundedRatio");
	}

	/**
	 * 国别
	 */
	public void setCountry(java.lang.String country) {
		set("country", country);
	}

	/**
	 * 国别
	 */
	public java.lang.String getCountry() {
		return get("country");
	}

}
