package com.kd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntBranchInfo<M extends BaseEntBranchInfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_branch_info";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 企业名
	 */
	public void setEntName(java.lang.String entName) {
		set("entName", entName);
	}

	/**
	 * 企业名
	 */
	public java.lang.String getEntName() {
		return get("entName");
	}

	/**
	 * 分支机构名称
	 */
	public void setBrName(java.lang.String brName) {
		set("brName", brName);
	}

	/**
	 * 分支机构名称
	 */
	public java.lang.String getBrName() {
		return get("brName");
	}

	/**
	 * 分支机构企业注册号
	 */
	public void setBrRegno(java.lang.String brRegno) {
		set("brRegno", brRegno);
	}

	/**
	 * 分支机构企业注册号
	 */
	public java.lang.String getBrRegno() {
		return get("brRegno");
	}

	/**
	 * 分支机构负责人
	 */
	public void setBrPrincipal(java.lang.String brPrincipal) {
		set("brPrincipal", brPrincipal);
	}

	/**
	 * 分支机构负责人
	 */
	public java.lang.String getBrPrincipal() {
		return get("brPrincipal");
	}

	/**
	 * 一般经营项目
	 */
	public void setCbuItem(java.lang.String cbuItem) {
		set("cbuItem", cbuItem);
	}

	/**
	 * 一般经营项目
	 */
	public java.lang.String getCbuItem() {
		return get("cbuItem");
	}

	/**
	 * 分支机构地址
	 */
	public void setBrAddr(java.lang.String brAddr) {
		set("brAddr", brAddr);
	}

	/**
	 * 分支机构地址
	 */
	public java.lang.String getBrAddr() {
		return get("brAddr");
	}

}
