package com.kd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLiquidationInfo<M extends BaseLiquidationInfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "liquidation_info";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 企业名
	 */
	public void setEntName(java.lang.String entName) {
		set("entName", entName);
	}

	/**
	 * 企业名
	 */
	public java.lang.String getEntName() {
		return get("entName");
	}

	/**
	 * 清算责任人
	 */
	public void setLigentity(java.lang.String ligentity) {
		set("ligentity", ligentity);
	}

	/**
	 * 清算责任人
	 */
	public java.lang.String getLigentity() {
		return get("ligentity");
	}

	/**
	 * 清算负责人
	 */
	public void setLigprincipal(java.lang.String ligprincipal) {
		set("ligprincipal", ligprincipal);
	}

	/**
	 * 清算负责人
	 */
	public java.lang.String getLigprincipal() {
		return get("ligprincipal");
	}

	/**
	 * 清算组成员
	 */
	public void setLiqMen(java.lang.String liqMen) {
		set("liqMen", liqMen);
	}

	/**
	 * 清算组成员
	 */
	public java.lang.String getLiqMen() {
		return get("liqMen");
	}

	/**
	 * 清算完结情况
	 */
	public void setLiGst(java.lang.String liGst) {
		set("liGst", liGst);
	}

	/**
	 * 清算完结情况
	 */
	public java.lang.String getLiGst() {
		return get("liGst");
	}

	/**
	 * 清算完结日期
	 */
	public void setLigEndDate(java.lang.String ligEndDate) {
		set("ligEndDate", ligEndDate);
	}

	/**
	 * 清算完结日期
	 */
	public java.lang.String getLigEndDate() {
		return get("ligEndDate");
	}

	/**
	 * 债务承接人
	 */
	public void setDebtTranee(java.lang.String debtTranee) {
		set("debtTranee", debtTranee);
	}

	/**
	 * 债务承接人
	 */
	public java.lang.String getDebtTranee() {
		return get("debtTranee");
	}

	/**
	 * 债权承接人
	 */
	public void setClaimTranee(java.lang.String claimTranee) {
		set("claimTranee", claimTranee);
	}

	/**
	 * 债权承接人
	 */
	public java.lang.String getClaimTranee() {
		return get("claimTranee");
	}

}
