package com.kd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntBasicInfo<M extends BaseEntBasicInfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_basic_info";

	/**
	 * 自增id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增id
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 企业名称
	 */
	public void setEnterpriseName(java.lang.String enterpriseName) {
		set("enterpriseName", enterpriseName);
	}

	/**
	 * 企业名称
	 */
	public java.lang.String getEnterpriseName() {
		return get("enterpriseName");
	}

	/**
	 * 法人姓名
	 */
	public void setFrName(java.lang.String frName) {
		set("frName", frName);
	}

	/**
	 * 法人姓名
	 */
	public java.lang.String getFrName() {
		return get("frName");
	}

	/**
	 * 统一信用代码
	 */
	public void setCreditCode(java.lang.String creditCode) {
		set("creditCode", creditCode);
	}

	/**
	 * 统一信用代码
	 */
	public java.lang.String getCreditCode() {
		return get("creditCode");
	}

	/**
	 * 工商注册号
	 */
	public void setRegNo(java.lang.String regNo) {
		set("regNo", regNo);
	}

	/**
	 * 工商注册号
	 */
	public java.lang.String getRegNo() {
		return get("regNo");
	}

	/**
	 * 注册资金(单位：万元)
	 */
	public void setRegCap(java.lang.String regCap) {
		set("regCap", regCap);
	}

	/**
	 * 注册资金(单位：万元)
	 */
	public java.lang.String getRegCap() {
		return get("regCap");
	}

	/**
	 * 注册币种
	 */
	public void setRegCapCur(java.lang.String regCapCur) {
		set("regCapCur", regCapCur);
	}

	/**
	 * 注册币种
	 */
	public java.lang.String getRegCapCur() {
		return get("regCapCur");
	}

	/**
	 * 开业日期（ YYYY-MM-DD）
	 */
	public void setEsDate(java.lang.String esDate) {
		set("esDate", esDate);
	}

	/**
	 * 开业日期（ YYYY-MM-DD）
	 */
	public java.lang.String getEsDate() {
		return get("esDate");
	}

	/**
	 * 经营期限自（ YYYY-MM-DD）
	 */
	public void setOpenFrom(java.lang.String openFrom) {
		set("openFrom", openFrom);
	}

	/**
	 * 经营期限自（ YYYY-MM-DD）
	 */
	public java.lang.String getOpenFrom() {
		return get("openFrom");
	}

	/**
	 * 经营期限至（ YYYY-MM-DD）
	 */
	public void setOpenTo(java.lang.String openTo) {
		set("openTo", openTo);
	}

	/**
	 * 经营期限至（ YYYY-MM-DD）
	 */
	public java.lang.String getOpenTo() {
		return get("openTo");
	}

	/**
	 * 企业（机构）类型
	 */
	public void setEnterpriseType(java.lang.String enterpriseType) {
		set("enterpriseType", enterpriseType);
	}

	/**
	 * 企业（机构）类型
	 */
	public java.lang.String getEnterpriseType() {
		return get("enterpriseType");
	}

	/**
	 * 经营状态 （ 在营、注销、吊销、其他）
	 */
	public void setEnterpriseStatus(java.lang.String enterpriseStatus) {
		set("enterpriseStatus", enterpriseStatus);
	}

	/**
	 * 经营状态 （ 在营、注销、吊销、其他）
	 */
	public java.lang.String getEnterpriseStatus() {
		return get("enterpriseStatus");
	}

	/**
	 * 注销日期
	 */
	public void setCancelDate(java.lang.String cancelDate) {
		set("cancelDate", cancelDate);
	}

	/**
	 * 注销日期
	 */
	public java.lang.String getCancelDate() {
		return get("cancelDate");
	}

	/**
	 * 吊销日期
	 */
	public void setRevokeDate(java.lang.String revokeDate) {
		set("revokeDate", revokeDate);
	}

	/**
	 * 吊销日期
	 */
	public java.lang.String getRevokeDate() {
		return get("revokeDate");
	}

	/**
	 * 注册地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	/**
	 * 注册地址
	 */
	public java.lang.String getAddress() {
		return get("address");
	}

	/**
	 * 许可经营项目
	 */
	public void setAbuItem(java.lang.String abuItem) {
		set("abuItem", abuItem);
	}

	/**
	 * 许可经营项目
	 */
	public java.lang.String getAbuItem() {
		return get("abuItem");
	}

	/**
	 * 一般经营项目
	 */
	public void setCbuItem(java.lang.String cbuItem) {
		set("cbuItem", cbuItem);
	}

	/**
	 * 一般经营项目
	 */
	public java.lang.String getCbuItem() {
		return get("cbuItem");
	}

	/**
	 * 经营（业务） 范围
	 */
	public void setOperateScope(java.lang.String operateScope) {
		set("operateScope", operateScope);
	}

	/**
	 * 经营（业务） 范围
	 */
	public java.lang.String getOperateScope() {
		return get("operateScope");
	}

	/**
	 * 经营(业务)范围及方式
	 */
	public void setOperateScopeAndForm(java.lang.String operateScopeAndForm) {
		set("operateScopeAndForm", operateScopeAndForm);
	}

	/**
	 * 经营(业务)范围及方式
	 */
	public java.lang.String getOperateScopeAndForm() {
		return get("operateScopeAndForm");
	}

	/**
	 * 登记机关
	 */
	public void setRegOrg(java.lang.String regOrg) {
		set("regOrg", regOrg);
	}

	/**
	 * 登记机关
	 */
	public java.lang.String getRegOrg() {
		return get("regOrg");
	}

	/**
	 * 最后年检年度
	 */
	public void setAncheYear(java.lang.String ancheYear) {
		set("ancheYear", ancheYear);
	}

	/**
	 * 最后年检年度
	 */
	public java.lang.String getAncheYear() {
		return get("ancheYear");
	}

	/**
	 * 行业门类代码
	 */
	public void setIndustryPhyCode(java.lang.String industryPhyCode) {
		set("industryPhyCode", industryPhyCode);
	}

	/**
	 * 行业门类代码
	 */
	public java.lang.String getIndustryPhyCode() {
		return get("industryPhyCode");
	}

	/**
	 * 国民经济行业代码
	 */
	public void setIndustryCode(java.lang.String industryCode) {
		set("industryCode", industryCode);
	}

	/**
	 * 国民经济行业代码
	 */
	public java.lang.String getIndustryCode() {
		return get("industryCode");
	}

	/**
	 * 国民经济行业名称
	 */
	public void setIndustryName(java.lang.String industryName) {
		set("industryName", industryName);
	}

	/**
	 * 国民经济行业名称
	 */
	public java.lang.String getIndustryName() {
		return get("industryName");
	}

	/**
	 * 实收资本
	 */
	public void setRecCap(java.lang.String recCap) {
		set("recCap", recCap);
	}

	/**
	 * 实收资本
	 */
	public java.lang.String getRecCap() {
		return get("recCap");
	}

	/**
	 * 原注册号
	 */
	public void setOriRegNo(java.lang.String oriRegNo) {
		set("oriRegNo", oriRegNo);
	}

	/**
	 * 原注册号
	 */
	public java.lang.String getOriRegNo() {
		return get("oriRegNo");
	}

	/**
	 * 行业门类名称
	 */
	public void setIndustryPhyName(java.lang.String industryPhyName) {
		set("industryPhyName", industryPhyName);
	}

	/**
	 * 行业门类名称
	 */
	public java.lang.String getIndustryPhyName() {
		return get("industryPhyName");
	}

	/**
	 * 未知
	 */
	public void setIdentityCardNt(java.lang.String identityCardNt) {
		set("identityCardNt", identityCardNt);
	}

	/**
	 * 未知
	 */
	public java.lang.String getIdentityCardNt() {
		return get("identityCardNt");
	}

	/**
	 * 最后年检日期
	 */
	public void setAncheDate(java.lang.String ancheDate) {
		set("ancheDate", ancheDate);
	}

	/**
	 * 最后年检日期
	 */
	public java.lang.String getAncheDate() {
		return get("ancheDate");
	}

	/**
	 * 核准时间
	 */
	public void setApprDate(java.lang.String apprDate) {
		set("apprDate", apprDate);
	}

	/**
	 * 核准时间
	 */
	public java.lang.String getApprDate() {
		return get("apprDate");
	}

}
