package com.kd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntChangeInfo<M extends BaseEntChangeInfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_change_info";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 企业名
	 */
	public void setEntName(java.lang.String entName) {
		set("entName", entName);
	}

	/**
	 * 企业名
	 */
	public java.lang.String getEntName() {
		return get("entName");
	}

	/**
	 * 变更日期
	 */
	public void setAltDate(java.lang.String altDate) {
		set("altDate", altDate);
	}

	/**
	 * 变更日期
	 */
	public java.lang.String getAltDate() {
		return get("altDate");
	}

	/**
	 * 变更事项
	 */
	public void setAltItem(java.lang.String altItem) {
		set("altItem", altItem);
	}

	/**
	 * 变更事项
	 */
	public java.lang.String getAltItem() {
		return get("altItem");
	}

	/**
	 * 变更前内容
	 */
	public void setAltBe(java.lang.String altBe) {
		set("altBe", altBe);
	}

	/**
	 * 变更前内容
	 */
	public java.lang.String getAltBe() {
		return get("altBe");
	}

	/**
	 * 变更后内容
	 */
	public void setAltAf(java.lang.String altAf) {
		set("altAf", altAf);
	}

	/**
	 * 变更后内容
	 */
	public java.lang.String getAltAf() {
		return get("altAf");
	}

}
