package com.kd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLegalPersonPositionInfo<M extends BaseLegalPersonPositionInfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "legal_person_position_info";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 法人姓名
	 */
	public void setFrName(java.lang.String frName) {
		set("frName", frName);
	}

	/**
	 * 法人姓名
	 */
	public java.lang.String getFrName() {
		return get("frName");
	}

	/**
	 * 企业（机构）名称
	 */
	public void setEntName(java.lang.String entName) {
		set("entName", entName);
	}

	/**
	 * 企业（机构）名称
	 */
	public java.lang.String getEntName() {
		return get("entName");
	}

	/**
	 * 企业（机构）类型
	 */
	public void setEntType(java.lang.String entType) {
		set("entType", entType);
	}

	/**
	 * 企业（机构）类型
	 */
	public java.lang.String getEntType() {
		return get("entType");
	}

	/**
	 * 统一信用代码
	 */
	public void setCreditCode(java.lang.String creditCode) {
		set("creditCode", creditCode);
	}

	/**
	 * 统一信用代码
	 */
	public java.lang.String getCreditCode() {
		return get("creditCode");
	}

	/**
	 * 注册号
	 */
	public void setRegNo(java.lang.String regNo) {
		set("regNo", regNo);
	}

	/**
	 * 注册号
	 */
	public java.lang.String getRegNo() {
		return get("regNo");
	}

	/**
	 * 注册资本(万元 )
	 */
	public void setRegCap(java.lang.String regCap) {
		set("regCap", regCap);
	}

	/**
	 * 注册资本(万元 )
	 */
	public java.lang.String getRegCap() {
		return get("regCap");
	}

	/**
	 * 注册资本币种
	 */
	public void setRegCapcur(java.lang.String regCapcur) {
		set("regCapcur", regCapcur);
	}

	/**
	 * 注册资本币种
	 */
	public java.lang.String getRegCapcur() {
		return get("regCapcur");
	}

	/**
	 * 注销日期
	 */
	public void setCanDate(java.lang.String canDate) {
		set("canDate", canDate);
	}

	/**
	 * 注销日期
	 */
	public java.lang.String getCanDate() {
		return get("canDate");
	}

	/**
	 * 吊销日期
	 */
	public void setRevDate(java.lang.String revDate) {
		set("revDate", revDate);
	}

	/**
	 * 吊销日期
	 */
	public java.lang.String getRevDate() {
		return get("revDate");
	}

	/**
	 * 企业状态
	 */
	public void setEntStatus(java.lang.String entStatus) {
		set("entStatus", entStatus);
	}

	/**
	 * 企业状态
	 */
	public java.lang.String getEntStatus() {
		return get("entStatus");
	}

	/**
	 * 登记机关
	 */
	public void setRegOrg(java.lang.String regOrg) {
		set("regOrg", regOrg);
	}

	/**
	 * 登记机关
	 */
	public java.lang.String getRegOrg() {
		return get("regOrg");
	}

	/**
	 * 职务
	 */
	public void setPosition(java.lang.String position) {
		set("position", position);
	}

	/**
	 * 职务
	 */
	public java.lang.String getPosition() {
		return get("position");
	}

	/**
	 * 是否法定代表人
	 */
	public void setLerepsign(java.lang.String lerepsign) {
		set("lerepsign", lerepsign);
	}

	/**
	 * 是否法定代表人
	 */
	public java.lang.String getLerepsign() {
		return get("lerepsign");
	}

	/**
	 * 开业日期
	 */
	public void setEsDate(java.lang.String esDate) {
		set("esDate", esDate);
	}

	/**
	 * 开业日期
	 */
	public java.lang.String getEsDate() {
		return get("esDate");
	}

}
