package com.kd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockFreezeInfo<M extends BaseStockFreezeInfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "stock_freeze_info";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 企业名
	 */
	public void setEntName(java.lang.String entName) {
		set("entName", entName);
	}

	/**
	 * 企业名
	 */
	public java.lang.String getEntName() {
		return get("entName");
	}

	/**
	 * 冻结文号
	 */
	public void setFroDocno(java.lang.String froDocno) {
		set("froDocno", froDocno);
	}

	/**
	 * 冻结文号
	 */
	public java.lang.String getFroDocno() {
		return get("froDocno");
	}

	/**
	 * 冻结机关
	 */
	public void setFroAuth(java.lang.String froAuth) {
		set("froAuth", froAuth);
	}

	/**
	 * 冻结机关
	 */
	public java.lang.String getFroAuth() {
		return get("froAuth");
	}

	/**
	 * 冻结起始日期
	 */
	public void setFroFrom(java.lang.String froFrom) {
		set("froFrom", froFrom);
	}

	/**
	 * 冻结起始日期
	 */
	public java.lang.String getFroFrom() {
		return get("froFrom");
	}

	/**
	 * 冻结截至日期
	 */
	public void setFroTo(java.lang.String froTo) {
		set("froTo", froTo);
	}

	/**
	 * 冻结截至日期
	 */
	public java.lang.String getFroTo() {
		return get("froTo");
	}

	/**
	 * 冻结金额
	 */
	public void setFroAm(java.lang.String froAm) {
		set("froAm", froAm);
	}

	/**
	 * 冻结金额
	 */
	public java.lang.String getFroAm() {
		return get("froAm");
	}

	/**
	 * 解冻机关
	 */
	public void setThawAuth(java.lang.String thawAuth) {
		set("thawAuth", thawAuth);
	}

	/**
	 * 解冻机关
	 */
	public java.lang.String getThawAuth() {
		return get("thawAuth");
	}

	/**
	 * 解冻文号
	 */
	public void setThawDocno(java.lang.String thawDocno) {
		set("thawDocno", thawDocno);
	}

	/**
	 * 解冻文号
	 */
	public java.lang.String getThawDocno() {
		return get("thawDocno");
	}

	/**
	 * 解冻日期
	 */
	public void setThawDate(java.lang.String thawDate) {
		set("thawDate", thawDate);
	}

	/**
	 * 解冻日期
	 */
	public java.lang.String getThawDate() {
		return get("thawDate");
	}

	/**
	 * 解冻说明
	 */
	public void setThawComment(java.lang.String thawComment) {
		set("thawComment", thawComment);
	}

	/**
	 * 解冻说明
	 */
	public java.lang.String getThawComment() {
		return get("thawComment");
	}

}
