package com.kd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseManagePerson<M extends BaseManagePerson<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "manage_person";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 姓名
	 */
	public java.lang.String getName() {
		return get("name");
	}

	/**
	 * 企业名
	 */
	public void setEntName(java.lang.String entName) {
		set("entName", entName);
	}

	/**
	 * 企业名
	 */
	public java.lang.String getEntName() {
		return get("entName");
	}

	/**
	 * 职务
	 */
	public void setPosition(java.lang.String position) {
		set("position", position);
	}

	/**
	 * 职务
	 */
	public java.lang.String getPosition() {
		return get("position");
	}

	/**
	 * 性别
	 */
	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	/**
	 * 性别
	 */
	public java.lang.String getSex() {
		return get("sex");
	}

}
