package com.kd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePunishmentInfo<M extends BasePunishmentInfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "punishment_info";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 企业名
	 */
	public void setEntName(java.lang.String entName) {
		set("entName", entName);
	}

	/**
	 * 企业名
	 */
	public java.lang.String getEntName() {
		return get("entName");
	}

	/**
	 * 案发时间
	 */
	public void setCaseTime(java.lang.String caseTime) {
		set("caseTime", caseTime);
	}

	/**
	 * 案发时间
	 */
	public java.lang.String getCaseTime() {
		return get("caseTime");
	}

	/**
	 * 案由
	 */
	public void setCaseReason(java.lang.String caseReason) {
		set("caseReason", caseReason);
	}

	/**
	 * 案由
	 */
	public java.lang.String getCaseReason() {
		return get("caseReason");
	}

	/**
	 * 案件类型
	 */
	public void setCaseType(java.lang.String caseType) {
		set("caseType", caseType);
	}

	/**
	 * 案件类型
	 */
	public java.lang.String getCaseType() {
		return get("caseType");
	}

	/**
	 * 执行类别
	 */
	public void setExeSort(java.lang.String exeSort) {
		set("exeSort", exeSort);
	}

	/**
	 * 执行类别
	 */
	public java.lang.String getExeSort() {
		return get("exeSort");
	}

	/**
	 * 案件结果
	 */
	public void setCaseResult(java.lang.String caseResult) {
		set("caseResult", caseResult);
	}

	/**
	 * 案件结果
	 */
	public java.lang.String getCaseResult() {
		return get("caseResult");
	}

	/**
	 * 处罚决定书签发日期
	 */
	public void setPendecissDate(java.lang.String pendecissDate) {
		set("pendecissDate", pendecissDate);
	}

	/**
	 * 处罚决定书签发日期
	 */
	public java.lang.String getPendecissDate() {
		return get("pendecissDate");
	}

	/**
	 * 处罚机关
	 */
	public void setPenAuth(java.lang.String penAuth) {
		set("penAuth", penAuth);
	}

	/**
	 * 处罚机关
	 */
	public java.lang.String getPenAuth() {
		return get("penAuth");
	}

	/**
	 * 主要违法事实
	 */
	public void setIllegFact(java.lang.String illegFact) {
		set("illegFact", illegFact);
	}

	/**
	 * 主要违法事实
	 */
	public java.lang.String getIllegFact() {
		return get("illegFact");
	}

	/**
	 * 处罚依据
	 */
	public void setPenBasis(java.lang.String penBasis) {
		set("penBasis", penBasis);
	}

	/**
	 * 处罚依据
	 */
	public java.lang.String getPenBasis() {
		return get("penBasis");
	}

	/**
	 * 处罚种类
	 */
	public void setPenType(java.lang.String penType) {
		set("penType", penType);
	}

	/**
	 * 处罚种类
	 */
	public java.lang.String getPenType() {
		return get("penType");
	}

	/**
	 *  处罚结果
	 */
	public void setPenResult(java.lang.String penResult) {
		set("penResult", penResult);
	}

	/**
	 *  处罚结果
	 */
	public java.lang.String getPenResult() {
		return get("penResult");
	}

	/**
	 * 处罚金额
	 */
	public void setPenAm(java.lang.String penAm) {
		set("penAm", penAm);
	}

	/**
	 * 处罚金额
	 */
	public java.lang.String getPenAm() {
		return get("penAm");
	}

	/**
	 * 处罚执行情况
	 */
	public void setPenExest(java.lang.String penExest) {
		set("penExest", penExest);
	}

	/**
	 * 处罚执行情况
	 */
	public java.lang.String getPenExest() {
		return get("penExest");
	}

	/**
	 * 行政处罚内容
	 */
	public void setPenContent(java.lang.String penContent) {
		set("penContent", penContent);
	}

	/**
	 * 行政处罚内容
	 */
	public java.lang.String getPenContent() {
		return get("penContent");
	}

}
